In [1]:
%matplotlib inline

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

# Intro to Deep Learning

## Live Demos

In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [5]:
# (2a + 3b) ** 2

def compute(a, b):
    return tf.pow(tf.add(tf.multiply(2,a), tf.multiply(3, b)), 2)

In [7]:
a = tf.constant(5)
b = tf.constant(10)

In [10]:
type(compute(a, b))

tensorflow.python.framework.ops.EagerTensor

In [11]:
compute(a, b).numpy()

1600

In [13]:
compute([1,2,3,5], [4,5,6,10])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [15]:
compute(np.array([1,2,3,5]), np.array([4,5,6,10]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [16]:
compute(5,10)

<tf.Tensor: shape=(), dtype=int32, numpy=1600>

In [29]:
def compute(a,b):
    return (2*a+3*b)**2

In [30]:
compute(2,3)

169

In [31]:
compute(1,b)

<tf.Tensor: shape=(), dtype=int32, numpy=1024>

In [32]:
compute(np.array([1,2,3,5]), np.array([4,5,6,10]))

array([ 196,  361,  576, 1600], dtype=int32)

In [33]:
@tf.function
def compute(a,b):
    return (2*a+3*b)**2

In [34]:
compute(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [35]:
compute(1,b)

<tf.Tensor: shape=(), dtype=int32, numpy=1024>

In [36]:
compute(np.array([1,2,3,5]), np.array([4,5,6,10]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [37]:
writer = tf.summary.create_file_writer("logs")
a, b = tf.constant([2,3,4]), tf.constant([3,4,5])
tf.summary.trace_on(graph=True, profiler = True)
result = compute(a,b)
print(result.numpy())
with writer.asdefault():
    tf.summary.trace_export